#!/usr/bin/env python3
"""
Find duplicates in Google Drive by (title, size) signature.
Outputs:
  drive_dupes_report.csv  — every duplicate group, marked which is keeper
  drive_dupes_summary.txt — totals
  trash_dupes.gs          — Apps Script that trashes the duplicates
"""
import json, csv
from collections import defaultdict
from datetime import datetime

INV = "organize/drive_inventory.json"
REPORT_CSV = "organize/drive_dupes_report.csv"
SUMMARY_TXT = "organize/drive_dupes_summary.txt"
APPS_SCRIPT = "organize/trash_dupes.gs"

inv = json.load(open(INV))
print(f"Loaded {len(inv)} files from Drive inventory.\n")

# Filter out folders + Google-native docs (no reliable size match)
binary_files = []
google_native = []
for f in inv:
    mime = f.get("mime", "")
    if mime == "application/vnd.google-apps.folder": continue
    if mime.startswith("application/vnd.google-apps."):
        google_native.append(f)
        continue
    binary_files.append(f)

print(f"  Folders skipped: {sum(1 for f in inv if f.get('mime') == 'application/vnd.google-apps.folder')}")
print(f"  Binary files (PDFs/spreadsheets/images): {len(binary_files)}")
print(f"  Google Docs/Sheets/Slides (separate dedup): {len(google_native)}\n")

# ─── BINARY FILE DEDUP by (title, size) ─────────────────────────────────────
groups_bin = defaultdict(list)
for f in binary_files:
    if not f.get("size"): continue
    key = (f["title"], int(f["size"]))
    groups_bin[key].append(f)

dup_groups_bin = {k: v for k, v in groups_bin.items() if len(v) > 1}
print(f"BINARY DUPLICATES")
print(f"  Duplicate groups: {len(dup_groups_bin)}")
redundant_bin = sum(len(v) - 1 for v in dup_groups_bin.values())
wasted_bytes = sum((len(v) - 1) * k[1] for k, v in dup_groups_bin.items())
print(f"  Redundant copies: {redundant_bin}")
print(f"  Wasted storage: {wasted_bytes / (1024*1024):.1f} MB\n")

# ─── GOOGLE NATIVE DEDUP by title only (less aggressive) ─────────────────────
groups_native = defaultdict(list)
for f in google_native:
    groups_native[f["title"]].append(f)
dup_groups_native = {k: v for k, v in groups_native.items() if len(v) > 1}
print(f"GOOGLE-NATIVE DUPLICATES (by title only — review more carefully)")
print(f"  Duplicate groups: {len(dup_groups_native)}")
redundant_native = sum(len(v) - 1 for v in dup_groups_native.values())
print(f"  Redundant copies: {redundant_native}\n")

# ─── KEEPER LOGIC: keep the newest mtime; tiebreak by shortest path ─────────
def pick_keeper(files):
    files_sorted = sorted(files, key=lambda f: (
        -datetime.fromisoformat(f["modifiedTime"].replace("Z","+00:00")).timestamp(),
        len(f.get("current_path", "")),
    ))
    return files_sorted[0], files_sorted[1:]

# ─── WRITE REPORT ───────────────────────────────────────────────────────────
with open(REPORT_CSV, "w", newline="") as out:
    w = csv.writer(out)
    w.writerow(["group_id","type","is_keeper","title","size","modified","owner","path","file_id","view_url"])
    gid = 0
    for (title, size), files in sorted(dup_groups_bin.items(), key=lambda kv: -kv[1][0]["size"] * (len(kv[1])-1)):
        gid += 1
        keeper, dupes = pick_keeper(files)
        w.writerow([gid, "binary", "YES", keeper["title"], keeper.get("size",""), keeper.get("modifiedTime",""), keeper.get("owner",""), keeper.get("current_path",""), keeper["id"], keeper.get("viewUrl","")])
        for d in dupes:
            w.writerow([gid, "binary", "no", d["title"], d.get("size",""), d.get("modifiedTime",""), d.get("owner",""), d.get("current_path",""), d["id"], d.get("viewUrl","")])
    for title, files in sorted(dup_groups_native.items()):
        gid += 1
        keeper, dupes = pick_keeper(files)
        w.writerow([gid, "google_native", "YES", keeper["title"], "(native)", keeper.get("modifiedTime",""), keeper.get("owner",""), keeper.get("current_path",""), keeper["id"], keeper.get("viewUrl","")])
        for d in dupes:
            w.writerow([gid, "google_native", "review", d["title"], "(native)", d.get("modifiedTime",""), d.get("owner",""), d.get("current_path",""), d["id"], d.get("viewUrl","")])

print(f"✓ Wrote {REPORT_CSV}\n")

# ─── BUILD APPS SCRIPT to trash binary dupes (safe: only same-size matches) ──
trash_ids = []
for (title, size), files in dup_groups_bin.items():
    keeper, dupes = pick_keeper(files)
    for d in dupes:
        # Only trash files the user owns (Drive blocks others)
        if d.get("owner") == "sunrize.invest@gmail.com":
            trash_ids.append({"id": d["id"], "title": d["title"], "size": size})

print(f"BINARY duplicates I CAN trash (owned by you): {len(trash_ids)}")
print(f"  (Files owned by others are excluded — Drive blocks foreign deletes)\n")

apps_script = '''/* trash_dupes.gs — generated by Claude
 * Sends duplicate files to Drive Trash. Files are recoverable from Trash for 30 days.
 * Re-runnable safely (skips files already trashed).
 */
function trashDupes() {
  const items = ''' + json.dumps([{"id": x["id"], "title": x["title"][:80]} for x in trash_ids], ensure_ascii=False) + ''';
  let trashed = 0, skipped = 0, errored = 0;
  const t0 = Date.now();
  const LIMIT = 5 * 60 * 1000; // 5 min — pause before Drive kills us
  const props = PropertiesService.getScriptProperties();
  let startIdx = parseInt(props.getProperty("idx") || "0", 10);
  for (let i = startIdx; i < items.length; i++) {
    if (Date.now() - t0 > LIMIT) {
      props.setProperty("idx", String(i));
      Logger.log("PAUSED at %s/%s. trashed=%s skipped=%s errored=%s. Run again to continue.", i, items.length, trashed, skipped, errored);
      return;
    }
    try {
      const f = DriveApp.getFileById(items[i].id);
      if (f.isTrashed()) { skipped++; continue; }
      f.setTrashed(true);
      trashed++;
      if (trashed % 50 === 0) Logger.log("trashed %s of %s", trashed, items.length);
    } catch (e) {
      errored++;
      if (errored <= 5) Logger.log("ERR %s: %s", items[i].id, e);
    }
  }
  props.deleteProperty("idx");
  Logger.log("DONE. trashed=%s, skipped(already-trashed)=%s, errored=%s, total=%s", trashed, skipped, errored, items.length);
}

function resetProgress() {
  PropertiesService.getScriptProperties().deleteProperty("idx");
  Logger.log("progress reset");
}

function restoreAll() {
  /* Recovery function — un-trash everything if you change your mind.
   * Only works within 30 days; after that Google purges Trash. */
  const items = '''+ json.dumps([{"id": x["id"]} for x in trash_ids], ensure_ascii=False) +''';
  let restored = 0;
  for (let i = 0; i < items.length; i++) {
    try {
      const f = DriveApp.getFileById(items[i].id);
      if (f.isTrashed()) { f.setTrashed(false); restored++; }
    } catch (e) {}
  }
  Logger.log("restored %s files from Trash", restored);
}
'''

with open(APPS_SCRIPT, "w") as f:
    f.write(apps_script)
print(f"✓ Wrote {APPS_SCRIPT}  ({len(trash_ids)} files queued to trash)\n")

# ─── SUMMARY ────────────────────────────────────────────────────────────────
summary = f"""DRIVE DEDUP SUMMARY
====================
Total Drive files scanned: {len(inv)}
  Folders: skipped
  Binary files (PDF, xlsx, docx, jpg, etc.): {len(binary_files)}
  Google-native (Docs, Sheets): {len(google_native)}

BINARY DUPLICATES (exact title+size match — high confidence)
  Duplicate groups: {len(dup_groups_bin)}
  Redundant copies: {redundant_bin}
  Wasted storage: {wasted_bytes / (1024*1024):.1f} MB
  Files I can trash for you (you own them): {len(trash_ids)}

GOOGLE-NATIVE DUPLICATES (title-only — review carefully)
  Duplicate groups: {len(dup_groups_native)}
  Redundant copies: {redundant_native}
  (NOT auto-trashed — these need manual review)

NEXT STEPS:
  1. Review: open organize/drive_dupes_report.csv
  2. To execute trash: paste organize/trash_dupes.gs into Apps Script editor, run trashDupes()
  3. To undo within 30 days: run restoreAll() in same script
"""
print(summary)
with open(SUMMARY_TXT, "w") as f:
    f.write(summary)
