/* trash_dupes_round2.gs — generated by Claude
 *
 * Round 2 of Drive dedup. Targets:
 *   - 2 older copies of Manhattan_Trophy_Hotel_Portfolio.pdf (keep newest)
 *   - "Copy of Copy of ..." files (definite duplicates)
 *   - 16 user-owned "Copy of ..." files where the prefix is a giveaway
 *
 * Re-runnable, recoverable from Trash for 30 days.
 */
function trashDupes2() {
  const items = [
    // ─── Manhattan_Trophy_Hotel_Portfolio.pdf (3 versions, keep newest from 7:04:49) ─────
    { id: "1F2VgXbNA1Hudg652MhLjU2DYMH5SBUmQ", title: "Manhattan_Trophy_Hotel_Portfolio.pdf (older 1, 6:57)" },
    { id: "1lyLZvB3nuD6LfW1oxyKYVi2w_TLPQ_xO", title: "Manhattan_Trophy_Hotel_Portfolio.pdf (older 2, 6:46)" },

    // ─── "Copy of Copy of" — definitely a copy-of-a-copy ──────────────────────
    { id: "1wsxP6rXT9V80GbbDIHQOTlJPCz2O_d9Wy_lBpSERlUA", title: "Copy of Copy of Co-Star: AB, Buyers/Sellers" },

    // ─── User-owned "Copy of" files — auto-trash, restore from Trash if wrong ─
    { id: "1bL8J9HVn2hcEcYys9ZZwq7yf7unOFuEpkh1AO57bn50", title: "Copy of First Deal Rental Property Underwriting Tool" },
    { id: "1LSS9D3mCnXvnhml1h6pd45LIeBUI2P-W", title: "Copy of TEMPLATE - PNW Statement - Blank.xlsx" },
    { id: "1x5NX0m-e8xORLl05Yiv17knKCDjpAch2", title: "Copy of Development Portfolio.docx (newer)" },
    { id: "1z35GdAzebf1OHjNKrAffymDx8Q_6DDez", title: "Copy of Development Portfolio.docx (older)" },
    { id: "10NKv7sT3kjSz2gX1WZWAGcPOBV2Qoyk1", title: "Copy of Advanced-Real-Estate-Purchase-Contract.webp" },
    { id: "1gonGIJ-Q9E-UHznjH2dye3nyXAoM1Hcm", title: "Copy of Website Design.docx" },
    { id: "1iBpR-82di44ml5tm8TbqdNb2NBssuG4t", title: "Copy of Naturopathic Doctor Contact.xlsx (15KB)" },
    { id: "1v6p0-TDNzObkSREPhuhjxS7JFGuhDHl9", title: "Copy of Naturopathic Doctor Contact.xlsx (11KB)" },
    { id: "1OFep2hbvVnGZ6hvLwryH_4npLQavM9d-zDyJcWoiRoE", title: "Copy of Sheet with GST" },
    { id: "1oKvf_b3gDviMwCeebRva4-qeyQEa9ZkUi5jIPwVsGUI", title: "Copy of Co-Star: AB, Buyers/Sellers" },
    { id: "1rZ0Rj3-UKWxYv8PBPek38xdcimV9G3Mi", title: "Copy of Co-Star: Edmonton MF Sellers" },
    { id: "1VsPiCtaA1-2wTIS5-h5L98PaDHgzVS6Dzk5mZGjV5PI", title: "Copy of COE Website 2025 Tax Sale Property List" },
    { id: "1536No_eMRP2XnDxHaYCFJYcb4kEXnZ0H", title: "Copy of Purchase Contract.pdf" },
    { id: "10L2dT-_gquC6Kqfkjg65eAivMHKO_sof", title: "Copy of Personal Net Worth Statement_Peakhill Capital.pdf" },
    { id: "1Ai6kXr0B_8fj52mriTT6i-j_rZnm3xum", title: "Copy of Personal-Financial-Statement.xlsx" },
  ];

  let trashed = 0, skipped = 0, errored = 0;
  for (let i = 0; i < items.length; i++) {
    try {
      const f = DriveApp.getFileById(items[i].id);
      if (f.isTrashed()) { skipped++; continue; }
      f.setTrashed(true);
      trashed++;
      Logger.log("✓ trashed: " + items[i].title);
    } catch (e) {
      errored++;
      Logger.log("⚠ error on " + items[i].title + ": " + e);
    }
  }
  Logger.log("");
  Logger.log("DONE. trashed=%s, already-trashed=%s, errored=%s, total=%s", trashed, skipped, errored, items.length);
}

function restoreRound2() {
  const ids = ["1F2VgXbNA1Hudg652MhLjU2DYMH5SBUmQ","1lyLZvB3nuD6LfW1oxyKYVi2w_TLPQ_xO","1wsxP6rXT9V80GbbDIHQOTlJPCz2O_d9Wy_lBpSERlUA","1bL8J9HVn2hcEcYys9ZZwq7yf7unOFuEpkh1AO57bn50","1LSS9D3mCnXvnhml1h6pd45LIeBUI2P-W","1x5NX0m-e8xORLl05Yiv17knKCDjpAch2","1z35GdAzebf1OHjNKrAffymDx8Q_6DDez","10NKv7sT3kjSz2gX1WZWAGcPOBV2Qoyk1","1gonGIJ-Q9E-UHznjH2dye3nyXAoM1Hcm","1iBpR-82di44ml5tm8TbqdNb2NBssuG4t","1v6p0-TDNzObkSREPhuhjxS7JFGuhDHl9","1OFep2hbvVnGZ6hvLwryH_4npLQavM9d-zDyJcWoiRoE","1oKvf_b3gDviMwCeebRva4-qeyQEa9ZkUi5jIPwVsGUI","1rZ0Rj3-UKWxYv8PBPek38xdcimV9G3Mi","1VsPiCtaA1-2wTIS5-h5L98PaDHgzVS6Dzk5mZGjV5PI","1536No_eMRP2XnDxHaYCFJYcb4kEXnZ0H","10L2dT-_gquC6Kqfkjg65eAivMHKO_sof","1Ai6kXr0B_8fj52mriTT6i-j_rZnm3xum"];
  let n = 0;
  for (const id of ids) {
    try { const f = DriveApp.getFileById(id); if (f.isTrashed()) { f.setTrashed(false); n++; } } catch (e) {}
  }
  Logger.log("restored %s files", n);
}
