// ─── RizeAI PDF Export ────────────────────────────────────────────────────
// Uses jsPDF to generate professional one-page deal summary PDFs.
// Three export functions: exportFlipPDF, exportBRRRRPDF, exportMFPDF

import jsPDF from "jspdf";

const DARK = "#ffffff";
const BLUE = "#3b9eff";
const GREEN = "#34d98a";
const RED = "#f25c5c";
const AMBER = "#f0a030";
const LIGHT_TEXT = "#dde4ef";
const SUB = "#6b7d96";

const fmt = (n) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n || 0);

const fmtPct = (n) =>
  isNaN(n) || !isFinite(n) ? "—" : `${(n * 100).toFixed(2)}%`;

function hexToRgb(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
}

function setFill(doc, hex) { const [r,g,b] = hexToRgb(hex); doc.setFillColor(r,g,b); }
function setDraw(doc, hex) { const [r,g,b] = hexToRgb(hex); doc.setDrawColor(r,g,b); }
function setTextColor(doc, hex) { const [r,g,b] = hexToRgb(hex); doc.setTextColor(r,g,b); }

// ── Shared helpers ──────────────────────────────────────────────────────────

function drawHeader(doc, title, address, city, verdict, verdictColor) {
  const W = 210, margin = 14;

  // Dark background header
  setFill(doc, "#ffffff");
  doc.rect(0, 0, W, 38, "F");

  // Logo
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  setTextColor(doc, BLUE);
  doc.text("Real", margin, 14);
  setTextColor(doc, LIGHT_TEXT);
  doc.text(" Deal", margin + 14, 14);

  // Date
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  setTextColor(doc, SUB);
  doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), W - margin, 10, { align: "right" });

  // Tool title
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  setTextColor(doc, LIGHT_TEXT);
  doc.text(title, margin, 24);

  // Address
  if (address || city) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    setTextColor(doc, SUB);
    doc.text(`${address || ""}${address && city ? " · " : ""}${city || ""}`, margin, 32);
  }

  // Verdict badge
  if (verdict) {
    const [vr, vg, vb] = hexToRgb(verdictColor || BLUE);
    doc.setFillColor(vr, vg, vb, 0.15);
    doc.roundedRect(W - 70, 16, 56, 16, 3, 3, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    setTextColor(doc, verdictColor || BLUE);
    doc.text(verdict, W - 42, 26, { align: "center" });
  }

  return 44; // starting Y
}

function drawSectionTitle(doc, text, y, color = BLUE) {
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  setTextColor(doc, color);
  doc.text(text.toUpperCase(), 14, y);
  setDraw(doc, "#1a2030");
  doc.setLineWidth(0.3);
  doc.line(14, y + 2, 196, y + 2);
  return y + 8;
}

function drawMetricBox(doc, x, y, w, h, label, value, color, sub) {
  setFill(doc, "#f8fafc");
  setDraw(doc, "#1a2030");
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 2, 2, "FD");

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  setTextColor(doc, color || BLUE);
  doc.text(value, x + w / 2, y + h / 2 - 1, { align: "center" });

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  setTextColor(doc, SUB);
  doc.text(label, x + w / 2, y + h / 2 + 7, { align: "center" });

  if (sub) {
    doc.setFontSize(6.5);
    doc.text(sub, x + w / 2, y + h / 2 + 13, { align: "center" });
  }
}

function drawRow(doc, label, value, y, bold = false, color = null) {
  doc.setFontSize(8.5);
  doc.setFont("helvetica", bold ? "bold" : "normal");
  setTextColor(doc, bold ? LIGHT_TEXT : SUB);
  doc.text(label, 18, y);

  doc.setFont("helvetica", bold ? "bold" : "normal");
  setTextColor(doc, color || (bold ? LIGHT_TEXT : "#8899b0"));
  doc.text(value, 196, y, { align: "right" });

  if (bold) {
    setDraw(doc, "#1a2030");
    doc.setLineWidth(0.2);
    doc.line(14, y + 1.5, 196, y + 1.5);
  }
  return y + 6;
}

function drawFooter(doc) {
  const W = 210, pageH = 297;
  setFill(doc, "#ffffff");
  doc.rect(0, pageH - 12, W, 12, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  setTextColor(doc, "#3a4a60");
  doc.text("Generated by rizeai.co — For informational purposes only. Not financial advice.", W / 2, pageH - 5, { align: "center" });
}

// ── FLIP PDF ────────────────────────────────────────────────────────────────

export function exportFlipPDF(v, c) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210, margin = 14;

  const isProfit = c.netProfit >= 0;
  const verdictColor = c.grade === "A" ? GREEN : c.grade === "B" ? BLUE : c.grade === "C" ? AMBER : RED;
  const verdict = `Grade ${c.grade} — ${isProfit ? "GO" : "No-Go"}`;

  let y = drawHeader(doc, "Fix & Flip Analyzer", v.address, v.city, verdict, verdictColor);

  // Top 4 metric boxes
  const boxW = (W - margin * 2 - 9) / 4;
  const boxes = [
    { label: "Net Profit", value: fmt(c.netProfit), color: isProfit ? GREEN : RED },
    { label: "Total ROI", value: fmtPct(c.roiTotal), color: BLUE },
    { label: "Profit Margin", value: fmtPct(c.profitMargin), color: c.profitMargin > 0.15 ? GREEN : AMBER },
    { label: "Ann. Cash-on-Cash", value: fmtPct(c.annualizedCoC), color: c.annualizedCoC > 0.2 ? GREEN : AMBER },
  ];
  boxes.forEach((b, i) => drawMetricBox(doc, margin + i * (boxW + 3), y, boxW, 26, b.label, b.value, b.color));
  y += 32;

  // Deal score bar
  setFill(doc, "#f8fafc");
  doc.roundedRect(margin, y, W - margin * 2, 10, 2, 2, "F");
  const barW = Math.min(c.score / 100, 1) * (W - margin * 2 - 4);
  setFill(doc, verdictColor);
  doc.roundedRect(margin + 2, y + 2, barW, 6, 1, 1, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  setTextColor(doc, LIGHT_TEXT);
  doc.text(`Deal Score: ${c.score}/100`, margin + 4, y + 6.5);
  y += 16;

  // Two columns
  const col1X = margin, col2X = W / 2 + 3, colW = W / 2 - margin - 3;

  // Left: Profit breakdown
  y = drawSectionTitle(doc, "Profit Breakdown", y);
  let leftY = y;
  const num = (val) => parseFloat(val) || 0;

  leftY = drawRow(doc, "After Repair Value (ARV)", fmt(v.arv), leftY, true);
  leftY = drawRow(doc, "— Purchase Price", `(${fmt(v.purchasePrice)})`, leftY);
  leftY = drawRow(doc, "— Repair Costs", `(${fmt(v.repairCosts)})`, leftY);
  leftY = drawRow(doc, "— Financing Costs", `(${fmt(c.totalFinancing)})`, leftY);
  leftY = drawRow(doc, "— Holding Costs", `(${fmt(c.totalHolding)})`, leftY);
  leftY = drawRow(doc, "— Buying Costs", `(${fmt(c.totalBuying)})`, leftY);
  leftY = drawRow(doc, "— Selling Costs", `(${fmt(c.totalSelling)})`, leftY);
  leftY = drawRow(doc, "NET PROFIT", fmt(c.netProfit), leftY, true, isProfit ? GREEN : RED);
  leftY = drawRow(doc, "Total All-In Cost", fmt(c.totalCosts), leftY);

  leftY += 6;
  leftY = drawSectionTitle(doc, "MAO Analysis", leftY);
  leftY = drawRow(doc, "Maximum Allowable Offer", fmt(c.mao), leftY, true, c.mao > 0 ? GREEN : RED);
  leftY = drawRow(doc, "Your Purchase Price", fmt(v.purchasePrice), leftY, true);
  const maoStatus = num(v.purchasePrice) <= c.mao
    ? `✓ Under MAO by ${fmt(c.mao - num(v.purchasePrice))}`
    : `⚠ Exceeds MAO by ${fmt(num(v.purchasePrice) - c.mao)}`;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  setTextColor(doc, num(v.purchasePrice) <= c.mao ? GREEN : RED);
  doc.text(maoStatus, col1X + 4, leftY);

  // Right: Key inputs + returns
  let rightY = y;
  rightY = drawSectionTitle(doc, "Key Inputs", rightY, "#6b7d96");
  rightY = drawRow(doc, "Hold Time", `${v.holdMonths} months`, rightY);
  rightY = drawRow(doc, "1st Loan Amount", fmt(v.loan1Amount), rightY);
  rightY = drawRow(doc, "Interest Rate", `${v.loan1Rate}% / yr`, rightY);
  rightY = drawRow(doc, "Property Tax (annual)", fmt(v.propTaxAnnual), rightY);
  rightY = drawRow(doc, "Realtor Commission", `${v.realtorPct}%`, rightY);
  rightY = drawRow(doc, "My Committed Cash", fmt(v.myCash), rightY);
  rightY += 6;
  rightY = drawSectionTitle(doc, "Return Analysis", rightY, "#6b7d96");
  rightY = drawRow(doc, "Purchase + Rehab ROI", fmtPct(c.roiPurchaseRehab), rightY);
  rightY = drawRow(doc, "Total Costs ROI", fmtPct(c.roiTotal), rightY, true);
  rightY = drawRow(doc, "Profit Margin", fmtPct(c.profitMargin), rightY);
  rightY = drawRow(doc, "Ann. Cash-on-Cash", fmtPct(c.annualizedCoC), rightY, true, c.annualizedCoC > 0 ? GREEN : RED);
  rightY = drawRow(doc, "Cost Per Sqft", fmt(c.costPerSqft), rightY);

  if (v.notes) {
    const maxY = Math.max(leftY, rightY) + 8;
    drawSectionTitle(doc, "Deal Notes", maxY);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    setTextColor(doc, SUB);
    const lines = doc.splitTextToSize(v.notes, W - margin * 2);
    doc.text(lines, margin, maxY + 7);
  }

  drawFooter(doc);
  const filename = (v.address || "flip-deal").replace(/[^a-zA-Z0-9]/g, "-").toLowerCase() + "-analysis.pdf";
  doc.save(filename);
}

// ── BRRRR PDF ────────────────────────────────────────────────────────────────

export function exportBRRRRPDF(form, calc) {
  if (!calc) return;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210, margin = 14;

  const isTrueBRRRR = calc.isTrueBRRRR;
  const verdictColor = isTrueBRRRR ? GREEN : calc.annualCF > 0 ? BLUE : RED;
  const verdict = isTrueBRRRR ? "True BRRRR ✓" : calc.annualCF > 0 ? "Partial BRRRR" : "Review Needed";

  let y = drawHeader(doc, "BRRRR Calculator", form.address, "", verdict, verdictColor);

  const boxW = (W - margin * 2 - 9) / 4;
  const boxes = [
    { label: "Cash Left In Deal", value: new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.cashLeftInDeal || 0), color: calc.isTrueBRRRR ? GREEN : AMBER },
    { label: "Monthly Cash Flow", value: new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.monthlyCF || 0), color: calc.monthlyCF > 0 ? GREEN : RED },
    { label: "DSCR", value: calc.dscr?.toFixed(2) ?? "—", color: calc.dscr >= 1.25 ? GREEN : calc.dscr >= 1 ? AMBER : RED },
    { label: "Equity Created", value: new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.equityCreated || 0), color: BLUE },
  ];
  boxes.forEach((b, i) => drawMetricBox(doc, margin + i * (boxW + 3), y, boxW, 26, b.label, b.value, b.color));
  y += 32;

  y = drawSectionTitle(doc, "BRRRR Strategy Results", y);
  y = drawRow(doc, "Total Cash In (Buy + Rehab + Closing)", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.totalCashIn || 0), y, true);
  y = drawRow(doc, "Refi Loan Amount (ARV × LTV)", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.refiLoanAmount || 0), y);
  y = drawRow(doc, "Cash Pulled Out at Refi", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.cashPulledOut || 0), y, true, calc.cashPulledOut >= 0 ? GREEN : RED);
  y = drawRow(doc, "Cash Left In Deal", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.cashLeftInDeal || 0), y, true, calc.isTrueBRRRR ? GREEN : AMBER);
  y += 4;
  y = drawRow(doc, "Monthly Rent (Effective)", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.effectiveRent || 0), y);
  y = drawRow(doc, "Annual NOI", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.noi || 0), y);
  y = drawRow(doc, "Refi Monthly Payment", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.refiMonthlyPayment || 0), y);
  y = drawRow(doc, "Monthly Cash Flow", new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(calc.monthlyCF || 0), y, true, calc.monthlyCF > 0 ? GREEN : RED);
  y = drawRow(doc, "DSCR", calc.dscr?.toFixed(2) ?? "—", y, true, calc.dscr >= 1.25 ? GREEN : calc.dscr >= 1 ? AMBER : RED);

  y += 6;
  y = drawSectionTitle(doc, "Key Inputs", y, "#6b7d96");
  y = drawRow(doc, "Purchase Price", `$${(parseFloat(form.purchasePrice)||0).toLocaleString()}`, y);
  y = drawRow(doc, "Rehab Budget", `$${(parseFloat(form.rehabBudget)||0).toLocaleString()}`, y);
  y = drawRow(doc, "ARV", `$${(parseFloat(form.arv)||0).toLocaleString()}`, y);
  y = drawRow(doc, "Refi LTV", `${form.refinanceLTV}%`, y);
  y = drawRow(doc, "Refi Rate", `${form.refiRate}%`, y);
  y = drawRow(doc, "Monthly Rent", `$${(parseFloat(form.monthlyRent)||0).toLocaleString()}`, y);

  drawFooter(doc);
  const filename = (form.address || "brrrr-deal").replace(/[^a-zA-Z0-9]/g, "-").toLowerCase() + "-brrrr.pdf";
  doc.save(filename);
}

// ── MULTIFAMILY PDF ──────────────────────────────────────────────────────────

export function exportMFPDF(inputs, calc) {
  if (!calc) return;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210, margin = 14;
  const f = n => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);
  const fp = n => isNaN(n)||!isFinite(n) ? "—" : `${(n*100).toFixed(2)}%`;

  const verdictColor = calc.verdict === "Strong Buy" ? GREEN : calc.verdict === "Buy" ? BLUE : calc.verdict === "Caution" ? AMBER : RED;
  let y = drawHeader(doc, "Multifamily Underwriter", inputs.address || "", "", calc.verdict || "—", verdictColor);

  const boxW = (W - margin * 2 - 9) / 4;
  const boxes = [
    { label: "Cap Rate", value: fp(calc.capRate), color: calc.capRate > 0.06 ? GREEN : AMBER },
    { label: "Cash-on-Cash", value: fp(calc.coc), color: calc.coc > 0.08 ? GREEN : AMBER },
    { label: "DSCR", value: calc.dscr?.toFixed(2) ?? "—", color: calc.dscr >= 1.25 ? GREEN : calc.dscr >= 1 ? AMBER : RED },
    { label: "NOI (Yr 1)", value: f(calc.noi), color: BLUE },
  ];
  boxes.forEach((b, i) => drawMetricBox(doc, margin + i * (boxW + 3), y, boxW, 26, b.label, b.value, b.color));
  y += 32;

  y = drawSectionTitle(doc, "Income & Expense Summary", y);
  y = drawRow(doc, "Gross Potential Rent (Year 1)", f(calc.gprCurrent), y);
  y = drawRow(doc, "— Vacancy Loss", `(${f(calc.vacancyLoss)})`, y);
  y = drawRow(doc, "+ Other Income", f(calc.otherAnnual), y);
  y = drawRow(doc, "Effective Gross Income", f(calc.egi), y, true);
  y = drawRow(doc, "— Total Operating Expenses", `(${f(calc.totalOpex)})`, y);
  y = drawRow(doc, "NET OPERATING INCOME (NOI)", f(calc.noi), y, true, calc.noi > 0 ? GREEN : RED);
  y = drawRow(doc, "— Annual Debt Service", `(${f(calc.annualDebtService)})`, y);
  y = drawRow(doc, "Cash Flow (Before Tax)", f(calc.cashFlow), y, true, calc.cashFlow > 0 ? GREEN : RED);

  y += 6;
  y = drawSectionTitle(doc, "Valuation & Returns", y, "#6b7d96");
  y = drawRow(doc, "Purchase Price", f(inputs.purchasePrice), y);
  y = drawRow(doc, "Down Payment", f(inputs.purchasePrice * inputs.downPct / 100), y);
  y = drawRow(doc, "Equity (Day 1)", f(calc.equity), y);
  y = drawRow(doc, "GRM", calc.grm?.toFixed(2) ?? "—", y);
  y = drawRow(doc, "Cap Rate", fp(calc.capRate), y, true);
  y = drawRow(doc, "Cash-on-Cash Return", fp(calc.coc), y, true, calc.coc > 0.08 ? GREEN : AMBER);
  y = drawRow(doc, "DSCR", calc.dscr?.toFixed(2) ?? "—", y, true, calc.dscr >= 1.25 ? GREEN : RED);

  y += 6;
  y = drawSectionTitle(doc, "Deal Checklist", y, "#6b7d96");
  const checks = [
    { label: "Cap Rate ≥ 5%", pass: calc.capRate >= 0.05 },
    { label: "DSCR ≥ 1.25", pass: calc.dscr >= 1.25 },
    { label: "Cash-on-Cash ≥ 8%", pass: calc.coc >= 0.08 },
    { label: "Positive Cash Flow", pass: calc.cashFlow > 0 },
    { label: "NOI covers 90% of debt service", pass: calc.noi >= calc.annualDebtService * 0.9 },
  ];
  checks.forEach(ch => {
    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    setTextColor(doc, ch.pass ? GREEN : RED);
    doc.text(`${ch.pass ? "✓" : "✗"}  ${ch.label}`, 18, y);
    y += 6;
  });

  drawFooter(doc);
  const filename = (inputs.address || "multifamily-deal").replace(/[^a-zA-Z0-9]/g, "-").toLowerCase() + "-mf.pdf";
  doc.save(filename);
}
